#ifndef __USER_IO_H
#define __USER_IO_H

#include "stm32f1xx_hal.h"

#define LED1_TOGGLE() HAL_GPIO_TogglePin(OUTPUT_LED1_GPIO_Port, OUTPUT_LED1_Pin)
#define LED2_TOGGLE() HAL_GPIO_TogglePin(OUTPUT_LED2_GPIO_Port, OUTPUT_LED2_Pin)
#define LED3_TOGGLE() HAL_GPIO_TogglePin(OUTPUT_LED3_GPIO_Port, OUTPUT_LED3_Pin)

#define LED1_ON() HAL_GPIO_WritePin(OUTPUT_LED1_GPIO_Port, OUTPUT_LED1_Pin, GPIO_PIN_RESET)
#define LED2_ON() HAL_GPIO_WritePin(OUTPUT_LED2_GPIO_Port, OUTPUT_LED2_Pin, GPIO_PIN_RESET)
#define LED3_ON() HAL_GPIO_WritePin(OUTPUT_LED3_GPIO_Port, OUTPUT_LED3_Pin, GPIO_PIN_RESET)

#define LED1_OFF() HAL_GPIO_WritePin(OUTPUT_LED1_GPIO_Port, OUTPUT_LED1_Pin, GPIO_PIN_SET)
#define LED2_OFF() HAL_GPIO_WritePin(OUTPUT_LED2_GPIO_Port, OUTPUT_LED2_Pin, GPIO_PIN_SET)
#define LED3_OFF() HAL_GPIO_WritePin(OUTPUT_LED3_GPIO_Port, OUTPUT_LED3_Pin, GPIO_PIN_SET)

extern void user_io_init(void);

#endif /* __USER_IO_H */
